name: senior-sync

services:

    mongo:
        image: mongo:8
        restart: unless-stopped
        volumes:
            - './mongodb-data:/data/db'
        networks:
            - mongo

    mongo-panel:
        image: mongo-express:latest
        restart: unless-stopped
        depends_on:
            - 'mongo'
        environment:
            ME_CONFIG_SITE_BASEURL: "/mongo/"
            ME_CONFIG_BASICAUTH_USERNAME: mongo
            ME_CONFIG_BASICAUTH_PASSWORD: quickly-obtuse-situation
            ME_CONFIG_MONGODB_SERVER: mongo
        networks:
            - mongo
            - nginx

    backend:
        image: 230daniel/private:senior-sync-backend
        restart: unless-stopped
        depends_on:
            - 'mongo'
        environment:
            MONGO_HOST: mongodb://mongo:27017
            FRONTEND_URL: https://utili.xyz:8443
            CORS_ALLOWED_ORIGINS: http://localhost:4173,http://localhost:5173
            EMAIL_SENDER: senior-sync@amazon-ses.utili.xyz
            EMAIL_RECIPIENT: daniel.baynton.026@cranfield.ac.uk
            AWS_DEFAULT_REGION: eu-west-2
            AWS_ACCESS_KEY_ID: null
            AWS_SECRET_ACCESS_KEY: null
        networks:
            - mongo
            - nginx

    frontend:
        image: 230daniel/private:senior-sync-frontend
        restart: unless-stopped
        volumes:
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
            - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8443:443'
        networks:
            - nginx

networks:
    mongo:
        driver: bridge
    nginx:
        driver: bridge
