name: senior-sync

services:

    mongo:
        image: mongo:8
        restart: unless-stopped
        volumes:
            - './mongodb-data:/data/db'
        networks:
            - backend

    mongo-panel:
        image: mongo-express:latest
        restart: unless-stopped
        depends_on:
            - 'mongo'
        environment:
            ME_CONFIG_SITE_BASEURL: "/mongo/"
            ME_CONFIG_BASICAUTH_USERNAME: mongo
            ME_CONFIG_BASICAUTH_PASSWORD: situation-obtuse-quickly
            ME_CONFIG_MONGODB_SERVER: mongo
        networks:
            - backend
            - frontend

    backend:
        build:
            context: './backend'
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        depends_on:
            - 'mongo'
        environment:
            MONGO_HOST: mongodb://mongo:27017
        networks:
            - backend
            - frontend

    frontend:
        build:
            context: './frontend'
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        volumes:
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
            - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8443:443'
        networks:
            - frontend

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
