name: senior-sync

services:

    backend:
        build:
            context: './backend'
            dockerfile: 'Dockerfile'
        restart: unless-stopped

    frontend:
        build:
            context: './frontend'
            dockerfile: 'Dockerfile'
        # volumes:
        #     - '/etc/letsencrypt/live/example.com:/ssl:ro'
        ports:
            # - '443:443'
            - '80:80'
        restart: unless-stopped
