name: senior-sync

services:

    database:
        image: mongo:8
        restart: unless-stopped
        volumes:
            - './database:/data/db'
        networks:
            - backend

    backend:
        build:
            context: './backend'
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        depends_on:
            - 'database'
        networks:
            - backend
            - frontend

    frontend:
        build:
            context: './frontend'
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        volumes:
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
        environment:
            SSL_CERTIFICATE_PATH: '/etc/letsencrypt/live/pi.utili.xyz/fullchain.pem'
            SSL_CERTIFICATE_KEY_PATH: '/etc/letsencrypt/live/pi.utili.xyz/privkey.pem'
        ports:
            - '443:443'
            - '80:80'
        networks:
            - frontend

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
