name: lint

on:
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '22.12'
    -
      name: Install dependencies
      run: |
        cd frontend
        npm ci - ignore-scripts
    -
      name: Lint 
      run: | 
        cd frontend
        npm run lint
